### ISSUE TITLE
Caught 'Error: Caught StopDispatching id'MSG_ID' exception, stopping dispatching.' exception, stopping dispatching.

### ISSUE THREAD

**Issue by ElectroMyStyle** [pikada-lab/icq-bot-nodejs#1]
Здравствуйте, API функционирует нормально?

Пытаюсь запустить пример из документации. Код максимально простой.
![icq-bot-api-code](https://user-images.githubusercontent.com/5159210/79848225-7acad600-83c9-11ea-9f0f-3d40d963a75a.PNG)

1. При запуске бота выбрасывается исключение: Caught 'Error: Caught StopDispatching id'MSG_ID' exception, stopping dispatching.' exception, stopping dispatching.
![icq-bot-api-exception](https://user-images.githubusercontent.com/5159210/79849007-8ec30780-83ca-11ea-8ecd-130415752f5f.PNG)

2. В документации рекомендуете создавать фильтры как новый объект:
![icq-bot-api-doc-code](https://user-images.githubusercontent.com/5159210/79848446-c2e9f880-83c9-11ea-9988-7b718e9432c5.PNG)
А на самом деле они уже создаются в классе Filter. 
![icq-bot-api-source-code](https://user-images.githubusercontent.com/5159210/79848778-3429ab80-83ca-11ea-9dca-254fe051adb8.PNG)
Это бы поправить в доке. А то исключение вываливается.

3. bot.startPolling() самостоятельно становится в поток ожидания новых событий или нет?

4. В вашем примере в обработчике у события `event` есть свойство `fromChatId`, но у меня оно `undefined`, это свойство еще доступно? Просто при обращении к свойству через полный путь `event.data.chat.chatId` оно возвращается нормально.

Использую:
OS: Window 7
NodeJS: 13.3.0
Запускаю через babel-node и nodemon
- `babel-node ./src/main.js --presets=env`
- `nodemon ./src/main.js --exec babel-node --presets=env`

**Comment by pikada-lab** [comment]
Благодарю за информацию, рассмотрел ваши проблемы. Попробую пройтись по пунктам. 

1. Я попробовал переписать ваш код и запустить на Ubuntu 18.04 / Windows 10 / MacOS Catalina командой 

```bash
node index.js
nodemon index.js
```

с пакетом 2.1.18. NodeJS: 12.* и 13.*. Проблем выявлено не было.
Ошибка типа **Cought** выбрасывается в случае неудачной обработки события. Такое может быть в нескольких случаях. Ошибка в функции обратного вызова и в случае отсутсивя обработчиков (Handler) при запущеном пулинге и приёме сообщения. Данный блок помещён в свой try контекст и в слшучае ошибки вызывает остановку пулинга.

2. Спасибо за предложение, думаю выпустить патч с более подробным описанием и примерами. Теперь о фильтрах. По сути все фильтры могут быть экспортированы на прямую, или написаны самостоятельно. Для удобства они объеденены в единый фасад, где можно взять параметризированные классы фильтров и создать их объекты или взять уже созданные не параметризированные. Если вам нужен оригинальный фильтр то используйте следующий интерфейс

```typescript
export interface Filter {
     filter(event: ICQEvent) : boolean
}
```

3. Старт пулинг выполнен рекурсивная функция из промисов. Я сталкивался с остановкой пулинга на убунту. Для этого можно вызвать 

```javascript
process.on('SIGINT', handle);
process.on('SIGTERM', handle);

function handle(signal) {
    console.log(`Received ${signal}`);
}
```

4. Свойство **fromChatId**  экспортируется для удобства работы у сообщений тип "message, editMessage, Pinned". Считаю, что тут вы правы, нужно добавить всем событиям это поле. Я  выпустил патч 2.1.19.

---

# Код при тестировании

```javascript
const ICQ = require('icq-bot').default;

const bot = new ICQ.Bot(ВАШ_ТОКЕН_БОТА);

let handlerNewMessage = new ICQ.Handler.Message(null, callbackHandlerNewMessage);

function callbackHandlerNewMessage(bot, event) {
    console.log(`New Message in ChatID: ${event.data.chat.chatId}; event.fromChatID = ${event.fromChatId}`);
    const chatId = event.data.chat.chatId;
    bot.sendText(chatId, "Привет!");
}

let handlerDeleteMessage = new ICQ.Handler.DeletedMessage(null, callbackHandlerDeleteMessage);

function callbackHandlerDeleteMessage(bot, event) {
    console.log(event);
    console.log(`Delete Message in ChatID: ${event.data.chat.chatId}; event.fromChatID = ${event.fromChatId}`);
    const chatId = event.data.chat.chatId;
    bot.sendText(chatId, "Зачем!");
}

try {

    bot.getDispatcher().addHandler(handlerNewMessage);
    bot.getDispatcher().addHandler(handlerDeleteMessage);

    bot.startPolling();

} catch (err) {
    console.log(err);
    console.log(err.stack);
}
```

**Comment by ElectroMyStyle** [comment]
Благодарю за тест. Скачал обновление и сейчас всё заработало, хоть и не сразу.
Пока пытался разобраться в чем же проблема, понял что ID сообщения попадало в кеш раньше, чем вызывался метод `check` в фильтре цикла. Как так происходило я так и не понял, как будто вызывалась закоментированная строка над циклом (что невозможно).
![icq-bot-dispatch-exception](https://user-images.githubusercontent.com/5159210/79922954-43960c80-843d-11ea-98e5-88fb800db788.PNG)

Теперь можно приступить к написанию бота, спасибо!

**Comment by pikada-lab** [comment]
Хэндлеры и фильтры, на мой взгляд не самое лучшее и очевидное решение для работы с событиями. Такая архитектура была заложена в проекте на питоне, и я делал её копию. Хэндлеры вызываются в диспетчере один за другим и срабатывают когда их check функция возвращает истину.
-  Сначала вызывается супер класс и проверяется в нём установленный вами фильтр или его отсутсвие - этот класс **HandlerBase**. Далее вызывается дополнительный фильтр классов потомка. В нашем случае **MessageHandler**, который отличает по параметру **event.type** сообщения **NEW_MESSAGE**. В случае с сообщением - ссылкой была проверена на отсутствие фильтров и тип **NEW_MESSAGE**. Её чек функция вернула истину, и обработчик обработал кол бэк.
- Потом следующий хэндлер с фильтром на ссылки проверил регулярным выражением что текст это ссылка и тип сообщения NEW_MESSAGE и тоже вернул истину. Ещё один кол бэк был обработан.

Такая логика считается правильной, хоть и неочевидной. Она заключается в том, что вы добавляете какое-то количество обработчиков и они срабатывают когда их условия проверки выполнены. Вы можете написать свои обработчики используя интерфейс:

```typescript
export interface Handler {
   check(event: ICQEvent, dispatcher: Dispatcher): boolean
   handle(event: ICQEvent, dispatcher: Dispatcher): void
}
```

---

Если вы планируете сложную логику обработки сообщений, то советую сделать ICQServiceEventHandler куда вынести следующую логику. 

В конструкторе сервис создаёте Subject (RxJS) и отдельным методом вызывается пулинг с одним обработчиком HandlerBase без фильтров, где в функции обратного вызова будет вызван метод Subject - next(event).  Далее в сервисе делаете метод , например методом getEvent(), где библиотека ICQ-BOT будет возвращать вам Observable<ICQEvent>. И далее обрабатывать все запросы своим собственным RX кодом. 

```typescript

interface MessagerServiceEventHandler {
    /// Конструктор без параметров
    startPooling(): void
    getEvent(): Observable<ICQEvent>
    /// Прочии нужные запросы к библиотеке  
}
```

Обратите внимание, что на момент запуска пулинга все подписчики должны быть уже подписаны на обработчик.

Так вам будет максимально понятно что происходит и как это работает. Также вы сможете отделить конкретную реализацию библиотеки от вашей бизнеслогики и если понадобится заменить её на Telegram bot или другую библиотеку без особых трудностей сделав адаптер событий.
