### ISSUE TITLE
ICQButton list

### ISSUE THREAD

**Issue by ElectroMyStyle** [pikada-lab/icq-bot-nodejs#3]
Здравствуйте, пытаюсь добавить список кнопок не в ряд, а списком по вертикали (то есть, каждая кнопка на отдельной строке). Вроде бы в оф. документации в параметр `inlineKeyboardMarkup` можно передать массив массивов, вот вырезка из документации: `inlineKeyboardMarkup` : `Это массив массивов с описанием кнопок. Верхний уровень это массив строк кнопок, ниже уровнем массив кнопок в конкретной строке`.

Я создаю заранее массив, затем в цикле наполняю его массивом создавая в нём 1-ну кнопку, вот так:
```javascript
let buttons = [];
for (let itemof items)
    buttons.push([new ICQ.Button(item.title, `{"action":"send","id":${item.id}}`)]);
```
В метод `sendText` передаю переменную `buttons` уже не оборачивая её в массив, чтобы добиться желаемого результат, но вываливается исключение. 

Подскажите, пожалуйста, как добиться списка кнопок по вертикали?
Судя по всему Вы этого не предусмотрели, так как в методе [getQueryStructure](https://github.com/pikada-lab/icq-bot-nodejs/blob/master/src/class/ICQButton.ts#L15), который вызывается в методе [Bot.getICQButtonList](https://github.com/pikada-lab/icq-bot-nodejs/blob/master/src/class/Bot.ts#L147) проверяются только свойства кнопки и возвращается нужный объект.
Так же получается, что в методе [Bot.getICQButtonList](https://github.com/pikada-lab/icq-bot-nodejs/blob/master/src/class/Bot.ts#L147) Вы создаёте массив, затем наполняете его объектами кнопок и оборачиваете массив с кнопками еще раз массивом в `return`. То есть, невозможно управлять верхнем уровнем массива - строками кнопок.

**Comment by pikada-lab** [comment]
Благодарю за обращение. Сейчас изучу вопрос и в течении дня сделаю релиз, если это необходимо.

**Comment by pikada-lab** [comment]
Изменил интерфейс на кнопки для кнопок. Теперь доступны следующие варианты:

```typescript
inlineKeyboardMarkup:  ICQButton | ICQButton[] | ICQButton[][]
```

Теперь вы можете положить кнопку, массив кнопок или массив массивов кнопок. Старый код по прежнему работает без изменений.

Пожалуйста проверьте работу метода в вашем коде и дайте обратную связь.

**Comment by ElectroMyStyle** [comment]
Добрый день, спасибо, теперь всё работает как хотелось бы.
