### ISSUE TITLE
ICQHttpClient.get

### ISSUE THREAD

**Issue by ElectroMyStyle** [pikada-lab/icq-bot-nodejs#5]
Здравствуйте, возникла проблема с отправкой текста.
Текст содержит символы с решёткой: (#1 - text)
В вашей функции [ICQHttpClient.get](https://github.com/pikada-lab/icq-bot-nodejs/blob/master/src/class/ICQHttpClient.ts#L11) параметры кодируются через **encodeURI** и получается, что решётка остаётся не закодированная, что конечно же не допустимо в GET параметре или просто сервер ICQ не воспринимает её в запросе. В конечном итоге бот присылает текст, который был до решётки, остальное куда-то исчезает. Почему не используете **encodeURIComponent**?
В кнопках еще не пробовал использовать символ решётки, но думаю там похожая ситуация.

**Comment by pikada-lab** [comment]
Благодарю за обращение.

Думаю хороший кейс для тестов. В ближайшее время решу вопрос.

**Comment by pikada-lab** [comment]
Обновите пакет до версии 2.1.34 

Код поправлен.

**Comment by ElectroMyStyle** [comment]
Обновил, вроде бы работает, думаю можно закрыть
