### ISSUE TITLE
sendFile caption encoding

### ISSUE THREAD

**Issue by ElectroMyStyle** [pikada-lab/icq-bot-nodejs#6]
Здравствуйте, столкнулся еще с одной проблемой: при отправке файла передаю русские символы и emoji, в результате получаются кракозябры и emoji не видны. При передаче латиницы всё нормально. Скорее всего надо делать URL Encode данных, но не уверен точно. По крайней мере в FormDataICQ данные текста никак не обрабатываются.

**Comment by pikada-lab** [comment]
FormDataICQ - это класс для создания тела пост запроса. Там нельзя никак кодировать сообщение. Всё должно происходить на стороне клиента. В противном случае файлы не будут передаваться. Я посмотрю что можно сделать. Пожалуйста пришлите клиентскую часть кода, как вы формируете отправку и что передаёте в функцию.

**Comment by ElectroMyStyle** [comment]
Да всё довольно просто:

```
await bot.sendFile(chatId, null, 'D:\\SERVER\\nodejs\\icq-bot-bot\\files\\mail.ru-logo.png', 'Тест кириллицы в подписи + emoji 😀');
```

Кодировка файла UTF-8 из которого выполняется метод.

Результат:

![FormData caption encoding](https://user-images.githubusercontent.com/5159210/83322722-c1caa780-a262-11ea-98a8-12025bf947f3.PNG)

А вот так выглядит имя файла, когда нажимаю `сохранить как`:

![Save path](https://user-images.githubusercontent.com/5159210/83322814-58976400-a263-11ea-99db-585cba90501e.PNG)

Посмотрел код, вот эта строка [FormDataICQ 24](https://github.com/pikada-lab/icq-bot-nodejs/blob/master/src/class/FormDataICQ.ts#L24) заточена только под Linux, так как разбивает пути типа `/var/www/server/file.png` в Windows у путей обратный слеш `D:\server\file.png`. Нужно как-то проверить тип OS тем самым выяснить какой разделитель использовать.

По поводу кодировки, [вот тут](https://tanaikech.github.io/2017/07/27/multipart-post-request-using-node.js/) есть пример как собирается запрос. Я немного его переписал и всё заработало [вот тут оставил рабочий пример](https://pastebin.com/iEJBDu7S)

Вот результат работы:

![image](https://user-images.githubusercontent.com/5159210/83325482-2858c100-a275-11ea-9ad6-e2c821979fae.png)

Был бы рад, если бы вы это реализовали в библиотеке.

**Comment by pikada-lab** [comment]
Ошибку поправил. Прошу обновить до версии 2.1.35 и посмотреть работоспособность.

**Comment by ElectroMyStyle** [comment]
Увы, но у меня не работает. Русские буквы и emoji выводятся как кракозябры. Когда обновляю с `npm` в `src/class/FormDataICQ.ts` код поправлен, но в папке `dist/class/FormDataICQ.js` код без конвертации. Я никогда не загружал свои пакеты в `npm`, но так как я не использую TS может быть надо как-то собрать проект в JS и обновить его в `npm`. Или он компилируется у меня на машине?

![image](https://user-images.githubusercontent.com/5159210/83329233-01a88380-a291-11ea-8539-2ac0118cd706.png)

**Comment by pikada-lab** [comment]
Прошу прощения. У меня неполадки с НПМ после перехода на платную версию. Пайплайн не работает временно. я выгрузил ещё раз, попробуйте снова.

**Comment by ElectroMyStyle** [comment]
Теперь работает, спасибо за обновление.

**Comment by pikada-lab** [comment]
Буду рад если найдёте ещё ошибки.

Спасибо.
