### ISSUE TITLE
Ошибки nginx от ICQ

### ISSUE THREAD

**Issue by ElectroMyStyle** [pikada-lab/icq-bot-nodejs#7]
Здравствуйте, возникла такая проблема. Так как мой бот загружает динамические файлы на сервер ICQ и я не контролирую их размер в данный момент. Иногда сервер ICQ возвращает nginx ошибку в виде html кода, например:

```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Так как [здесь](https://github.com/pikada-lab/icq-bot-nodejs/blob/master/src/class/ICQHttpClient.ts#L84) ответ сразу разбирается как JSON, скрипт просто падает с ошибкой не смотря на все мои `try {} catch ()`:
```
undefined:1
<html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (D:\SERVER\nodejs\icq-bot-bot\node_modules\←[4micq-bot←[24m\dist\class\ICQHttpClient.js:70:34)
←[90m    at IncomingMessage.emit (events.js:215:7)←[39m
←[90m    at endReadableNT (_stream_readable.js:1183:12)←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:80:21)←[39m
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! icq-bot-bot@1.0.0 start: `node --experimental-modules --experimental-json-modules --es-module-specifier-resolution=node main.mjs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the icq-bot-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-05-30T20_49_06_472Z-debug.log
Waiting for the debugger to disconnect...

Process finished with exit code 1
```

Хорошо бы проверять ответ сервера ICQ на пустой ответ или на `<html>` и как-то просто реджектить запрос в случае такого ответа от сервера или пустого ответа от ICQ в методах `get` и `post`, так как `JSON.parse()` на данный момент убивает работу скрипта.

Как воспроизвести ошибку: сейчас можно загрузить максимум 15 Mb через бота, в дальнейшем можно будет 50 Mb (так как есть ошибка на стороне ICQ, в данный момент max 15 Mb), так вот, я пытался загрузить файл размером 40 Mb и сервер вернул ошибку.

**Comment by pikada-lab** [comment]
Могу добавить ограничение в конфигурации бота и имитировать ошибку в виде сообщения похожего на ответ сервера.

**Comment by ElectroMyStyle** [comment]
Ну можно и так, да или хотя бы просто выбрасывать исключение, но чтобы скрипт не падал.

**Comment by pikada-lab** [comment]
Я поговорил с тех поддержкой, подождём исправление апи. Потому что правильное поведение при ответе сервера 500 должно быть выыключение программы.

**Comment by ElectroMyStyle** [comment]
Хорошо, подождём. У себя я пока залатал эту проблему собственными методами.
